language: go
sudo :required

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

services:
  - docker

before_install:
    - curl -L https://github.com/docker/compose/releases/download/1.4.2/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin

script: make test
